- name: check ping
  hosts: app
  gather_facts: no
  vars_files:
    - ../vars/jits_var.yml

  tasks:
    - name: ping hosts
      win_ping:
      register: ping_status
      
    - name: print ping status
      debug:
        msg: "ping status for {{ inventory_hostname }}:{{ ping_status.ping }}"

    - name: verify the services before start stop
      ansible.windows.win_service_info:
        name: "{{ item }}"
      loop: "{{ services }}"
      register: services_info_result

    - name: display service state status
      debug:
        msg: "service {{ item.item }} is currently in {{ item.services[0].state }} state"
      loop: "{{ services_info_result.results }}"

    - name: checking if services are in running state
      debug:
        msg: "service {{ item.item }} is in running state, taking action to stop"
      when: item.exists and item.services[0].state == 'started'
      loop: "{{ services_info_result.results }}"

    - name: stop services that are in running state
      ansible.windows.win_service:
        name: "{{ item.item }}"
        state: stopped
      when: item.exists and item.services[0].state == 'started'
      loop: "{{ services_info_result.results }}"
      register: service_stop_result

    - name: check final status of services after attempting to stop
      debug:
        msg: "service {{ item.item }} is now in {{ item.services[0].state }} state"
      loop: "{{ service_stop_result.results }}"
      when: item.changed

