- name: print the variable for Primary Node
  debug:
    msg: "Primary node name is {{ Prim_Node }}"

- name: print the variable for Secondary Node
  debug:
    msg: "Secondary node name is {{ Sec_Node }}"

- name: create script directory
  win_file:
    path: C:\Data\myscript
    state: directory

- block:
    - name: copy health script
      win_template:
        src: myhealth1.sql.j2
        dest: C:\Data\myscript\myhealth1.sql

    - name: copy health script
      win_template:
        src: myhealth2.sql.j2
        dest: C:\Data\myscript\myhealth2.sql
  when: "'primary' in group_names"

- block:
    - name: copy health script
      win_template:
        src: myhealth3.sql.j2
        dest: C:\Data\myscript\myhealth3.sql

    - name: copy health script
      win_template:
        src: myhealth4.sql.j2
        dest: C:\Data\myscript\myhealth4.sql
  when: "'secondary' in group_names"
